# -*- coding: utf-8 -*-
"""test_scientific_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I4-Ryg4GmMUYtKwD4B9j5T0gpj7_pg4n
"""

import unittest
import math
from scientific_calculator import sin, cos, tan, sqrt, log

class TestScientificCalculator(unittest.TestCase):

    def test_sin_positive_input(self):
        self.assertAlmostEqual(sin(90), math.sin(math.radians(90)))

    def test_sin_negative_input(self):
        self.assertAlmostEqual(sin(-90), math.sin(math.radians(-90)))

    def test_sin_zero_input(self):
        self.assertAlmostEqual(sin(0), math.sin(math.radians(0)))

    def test_sin_non_numeric_input(self):
        with self.assertRaises(TypeError):
            sin("hello")

    def test_cos_positive_input(self):
        self.assertAlmostEqual(cos(0), math.cos(math.radians(0)))

    def test_tan_positive_input(self):
        self.assertAlmostEqual(tan(45), math.tan(math.radians(45)))

    def test_sqrt_positive_input(self):
        self.assertAlmostEqual(sqrt(9), math.sqrt(9))

    def test_log_positive_input(self):
        self.assertAlmostEqual(log(10), math.log10(10))

    def test_non_numeric_input(self):
        with self.assertRaises(TypeError):
            cos("hello")
        with self.assertRaises(TypeError):
            tan("hello")
        with self.assertRaises(TypeError):
            sqrt("hello")
        with self.assertRaises(TypeError):
            log("hello")

    def test_log_invalid_input(self):
        with self.assertRaises(ValueError):
            log(-1)

if __name__ == '__main__':
    unittest.main()